### ISSUE TITLE
[Linux]:loading vaapi driver is wrong

### ISSUE THREAD

**Issue by naoya-oyama** [lu-zero/mfx_dispatch#11]
Loading vaapi driver for Intel is wrong.
NG: i965.so
OK: iHD.so

If using the mfx_dispatch provided in the MSDK package, there has no problem.

Sample code:

```
int main(int argc, char **argv)
{
    mfxStatus sts = MFX_ERR_NONE;
    mfxSession session;
    mfxVersion version;

    version.Minor = 0;
    version.Major = 1;

    sts = MFXInit(MFX_IMPL_HARDWARE, &version, &session);

    if (sts != MFX_ERR_NONE) {
        printf("MFXInit error %x\n", sts);
        return sts;
    }

    sts = mfx_sethandle(&session);
    if (sts != MFX_ERR_NONE) {
        printf("sethandle error %x\n", sts);
        return sts;
    }
    return 0;
}
```
## MSDK result:

$ ./a.out
libva info: VA-API version 0.35.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0

---
## lu-zero mfx_dispath result:

$ ./a.out
libva info: VA-API version 0.35.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965

---

**Comment by lu-zero** [comment]
It depends on which drivers you are using and are available, my version has an experimental glue-code to automatically pick set the handle. I'll try to improve it (and maybe try to figure out a way to make so the glue can be disabled).

Thanks a lot for the report.

**Comment by lu-zero** [comment]
Anton improved the glue-code, does it work for you now?

**Comment by lu-zero** [comment]
It seems working fine.
