### ISSUE TITLE
[Linux]undefined reference to `MFX::SelectImplementationType

### ISSUE THREAD

**Issue by T-bagwell** [lu-zero/mfx_dispatch#14]
compile the mfx_dispatch for the ffmpeg
autoreconf -i`
./configure --prefix=/usr/ --libdir=/usr/lib64
make;make install

when configure the ffmpeg source code with

./confgiure --enable-libmfx;the config.log bellow

check_pkg_config libmfx mfx/mfxvideo.h MFXInit
pkg-config --exists --print-errors libmfx
check_func_headers mfx/mfxvideo.h MFXInit -lmfx -lstdc++ -lva-drm -lva-x11 -lva
check_ld cc -lmfx -lstdc++ -lva-drm -lva-x11 -lva
check_cc
BEGIN /tmp/ffconf.G1Df1vFA.c
    1   #include <mfx/mfxvideo.h>
    2   long check_MFXInit(void) { return (long) MFXInit; }
    3   int main(void) { return 0; }
END /tmp/ffconf.G1Df1vFA.c
gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -std=c99 -fomit-frame-pointer -pthread -c -o /tmp/ffconf.hy5b3DdR.o /tmp/ffconf.G1Df1vFA.c
gcc -Wl,--as-needed -Wl,-z,noexecstack -o /tmp/ffconf.0PLCgiqR /tmp/ffconf.hy5b3DdR.o -lmfx -lstdc++ -lva-drm -lva-x11 -lva -lm -lz -pthread
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libmfx.so: undefined reference to `MFX::SelectImplementationType(unsigned int, int*, unsigned int*, unsigned int*)'
collect2: error: ld returned 1 exit status
ERROR: libmfx not found using pkg-config

**Comment by lu-zero** [comment]
FFmpeg is not supported. Please try with Libav and report back.
