### ISSUE TITLE
Building lu-zero/libav

### ISSUE THREAD

**Issue by exxamedia** [lu-zero/mfx_dispatch#16]
Using clean Centos 6.6 with Intel MSDK
Installed libva, libdrm etc, then installed mfx_dispatch:
autoreconf -i && ./configure --prefix...  &&  make && make install

got libav from lu-zero/libav

Configured: 

PKG_CONFIG_PATH=/encoder/lib/pkgconfig LDFLAGS="-L/encoder/lib -L/opt/intel/mediasdk/lib -L/opt/intel/mediasdk/lib64"  CFLAGS="-I/encoder/include/  -I/opt/intel/mediasdk/include/" ./configure --prefix=/encoder --enable-libmfx

make
....
CC      libavcodec/qsv.o
In file included from /encoder/include/mfx/mfxsession.h:32,
                 from /encoder/include/mfx/mfxvideo.h:32,
                 from libavcodec/qsv.c:27:
/encoder/include/mfx/mfxcommon.h:81: warning: declaration does not declare anything
/encoder/include/mfx/mfxcommon.h:101: warning: declaration does not declare anything
/encoder/include/mfx/mfxcommon.h:103: warning: declaration does not declare anything
/encoder/include/mfx/mfxcommon.h:127: warning: declaration does not declare anything
/encoder/include/mfx/mfxcommon.h:129: warning: declaration does not declare anything
In file included from /encoder/include/mfx/mfxvstructures.h:30,
                 from /encoder/include/mfx/mfxvideo.h:33,
                 from libavcodec/qsv.c:27:
/encoder/include/mfx/mfxstructures.h:51: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:54: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:55: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:79: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:83: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:84: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:169: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:181: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:188: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:198: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:204: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:252: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:258: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:263: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:268: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:275: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:282: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:288: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:289: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:306: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:714: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:718: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:719: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:1004: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:1008: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:1012: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:1146: warning: declaration does not declare anything
/encoder/include/mfx/mfxstructures.h:1165: warning: declaration does not declare anything
libavcodec/qsv.c: In function "qsv_init_session":
libavcodec/qsv.c:107: warning: braces around scalar initializer
libavcodec/qsv.c:107: warning: (near initialization for "ver.Version")
libavcodec/qsv.c:107: warning: excess elements in scalar initializer
libavcodec/qsv.c:107: warning: (near initialization for "ver.Version")
libavcodec/qsv.c: In function "ff_qsv_init":
libavcodec/qsv.c:159: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:160: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:161: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:163: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:164: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:165: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:166: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:167: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:168: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c:169: error: "mfxVideoParam" has no member named "mfx"
libavcodec/qsv.c: In function "alloc_frame":
libavcodec/qsv.c:198: error: "mfxFrameInfo" has no member named "Width"
libavcodec/qsv.c:199: error: "mfxFrameInfo" has no member named "Height"
libavcodec/qsv.c:202: error: "mfxFrameData" has no member named "PitchLow"
libavcodec/qsv.c:203: error: "mfxFrameData" has no member named "Y"
libavcodec/qsv.c:204: error: "mfxFrameData" has no member named "UV"
libavcodec/qsv.c: In function "ff_qsv_decode":
libavcodec/qsv.c:279: warning: braces around scalar initializer
libavcodec/qsv.c:279: warning: (near initialization for "bs.DecodeTimeStamp")
libavcodec/qsv.c:279: warning: braces around scalar initializer
libavcodec/qsv.c:279: warning: (near initialization for "bs.DecodeTimeStamp")
make: *** [libavcodec/qsv.o] Error 1

Any advise please.
Am I missing some additional library?

**Comment by lu-zero** [comment]
Please use libav for git.libav.org and make sure you installed `mfx_dispatch` and do not use those flags overrides.

**Comment by lu-zero** [comment]
If it is still a problem please reopen the bug.
