### ISSUE TITLE
No video with ffplay and mediasdk 2015rc6

### ISSUE THREAD

**Issue by DanielFragaBR** [lu-zero/mfx_dispatch#18]
I compiled mfx_dispatch and installed mediasdk 2015rc6 (community version) on Linux. Everything configured and when I try to "ffplay -vcodec h264_qsv..." it doesn't show the video (it just plays the audio).

I'm using it on Linux with ffmpeg 2.8. My question is: I imagine it can't work with Sandy Bridge, right? At least the mediasdk says I need at least a Haswell. Is this the problem or is there some workaround to make it work on Sandy Bridge too?

Ps: just for comparison, gst-play (from gstreamer) can use libva and hardware accelerate the video decoding, so I suppose mediasdk is important just for the encoding, but not the decoding, since it could be done with libva alone, right?

**Comment by lu-zero** [comment]
FFmpeg is not supported.
