### ISSUE TITLE
ubuntu 15.10 intel graphics stack and ffmpeg

### ISSUE THREAD

**Issue by PipOlt** [lu-zero/mfx_dispatch#23]
Hello!
just trying to firgure out if mfx_dispatch works with the current intel graphics stack for Ubuntu 15.10 and ffmpeg 2.8. I can't really find the actual requirements. Everything compiles correctly but I get an Error trying to encode a sample Video:
Error initializing an internal MFX session
So I need to install the libva and libdrm from the current Intel Media Server Studio or did I missed some configs for getting everything stick together? I would prefer not to change my current Kernel for qsv hardware accleration.

**Comment by madsnow** [comment]
Having the same issue on 15.10. Did you find a solution?

**Comment by lu-zero** [comment]
ffmpeg is not supported to begin with.

**Comment by PipOlt** [comment]
Thank you for the response. The question wasn't ffmpeg specific, but maybe this wasn't clear. I tried to ask if mfx-dispatch works with the latest Intel graphics stack from [here](https://01.org/linuxgraphics/downloads/intel-graphics-installer-linux-1.2.1). Or do I have to install the Intel Media SDK with the patched Kernel from [here](https://software.intel.com/en-us/intel-media-server-studio).
