### ISSUE TITLE
Linux Compile

### ISSUE THREAD

**Issue by beastwick** [lu-zero/mfx_dispatch#24]
I understand if this gets closed out quickly because it's a compilation issue and not a coding error. I'm not sure that I understand the dependencies correctly.

If I am on Linux then I don't need to install the Media SDK if I have libva installed?

Right now that is the case here. I am hesitant to install the SDK because I don't know where it puts everything. Does it default to /opt for all its files?

I compiled your dispatcher and pointed it to my ffmpeg_build directory for installation. This is exactly what I have done so far:

libmfx install
autoreconf -i
./configure --prefix=$HOME/ffmpeg_build
make -j 18
make install
 
PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/bin" --pkg-config-flags="--static" --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libmfx
 
tail config.log
    3   int main(void) { return 0; }
END /tmp/ffconf.srZzUVvD.c
gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -I/home/brian/ffmpeg_build/include -std=c99 -fomit-frame-pointer -pthread -I/home/brian/ffmpeg_build/include -I/home/brian/ffmpeg_build/include -L/home/brian/ffmpeg_build/lib -c -o /tmp/ffconf.T8XBOPjH.o /tmp/ffconf.srZzUVvD.c
gcc -L/home/brian/ffmpeg_build/lib -Wl,--as-needed -Wl,-z,noexecstack -I/home/brian/ffmpeg_build/include -L/home/brian/ffmpeg_build/lib -o /tmp/ffconf.knjn9Kq7 /tmp/ffconf.T8XBOPjH.o -lmfx -lstdc++ -ldl -L/home/brian/ffmpeg_build/lib -lfdk-aac -lm -lm -lz -pthread
/home/brian/ffmpeg_build/lib/libmfx.a(libmfx_la-main.o): In function `init_internal_hwctx':
/home/brian/mfx_dispatch/src/main.cpp:930: undefined reference to `mfx_allocate_va'
/home/brian/ffmpeg_build/lib/libmfx.a(libmfx_la-main.o): In function `MFXClose':
/home/brian/mfx_dispatch/src/main.cpp:531: undefined reference to `mfx_deallocate_va'
collect2: error: ld returned 1 exit status
ERROR: libmfx not found using pkg-config

I'm not sure where to go from here. I couldn't find much help on IRC and it's not really an FFMPEG problem.

**Comment by lu-zero** [comment]
The dispatcher on linux requires libva but the configure doesn't error out apparently I'll try to fix it later. In the mean time you might check that you have the libva headers and pkg-config files installed.

**Comment by beastwick** [comment]
Thanks for getting back to me so quickly.

I am on Fedora 22 and I have libva, libva-devel, libva-utils installed. 

pkgconfig directory:

/home/brian/ffmpeg_build/lib/pkgconfig ls
fdk-aac.pc     
libavdevice.pc  
libavformat.pc 
libmfx.pc      
libswresample.pc  
ogg.pc   
vorbisenc.pc  
vorbis.pc
x264.pc
libavcodec.pc 
libavfilter.pc  
libavutil.pc   
libpostproc.pc 
libswscale.pc     
opus.pc 
vorbisfile.pc  
vpx.pc

libmfx.pc:

cat libmfx.pc
prefix=//home/brian/ffmpeg_build
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libmfx
Description: Intel Media SDK Dispatched static library
Version: 1.16
Libs: -L${libdir} -lmfx -lstdc++ -ldl -lva-drm -lva  -lva-x11 -lva
Libs.private:
Cflags: -I${includedir}

end of make:

make[1]: Entering directory '/home/brian/mfx_dispatch'
/usr/bin/mkdir -p '//home/brian/ffmpeg_build/lib'
/bin/sh ./libtool   --mode=install /usr/bin/install -c   libmfx.la '//home/brian/ffmpeg_build/lib'
libtool: install: /usr/bin/install -c .libs/libmfx.lai //home/brian/ffmpeg_build/lib/libmfx.la
libtool: install: /usr/bin/install -c .libs/libmfx.a //home/brian/ffmpeg_build/lib/libmfx.a
libtool: install: chmod 644 //home/brian/ffmpeg_build/lib/libmfx.a
libtool: install: ranlib //home/brian/ffmpeg_build/lib/libmfx.a
libtool: finish: PATH="/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/brian/.local/bin:/home/brian/bin:/sbin" ldconfig -n //home/brian/ffmpeg_build/lib
----------------------------------------------------------------------
Libraries have been installed in:
   //home/brian/ffmpeg_build/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '//home/brian/ffmpeg_build/lib/pkgconfig'
 /usr/bin/install -c -m 644 libmfx.pc '//home/brian/ffmpeg_build/lib/pkgconfig'
 /usr/bin/mkdir -p '//home/brian/ffmpeg_build/include/mfx'
 /usr/bin/install -c -m 644 mfx/mfxastructures.h mfx/mfxaudio.h mfx/mfxcommon.h mfx/mfxdefs.h mfx/mfxenc.h mfx/mfxjpeg.h mfx/mfxla.h mfx/mfxmvc.h mfx/mfxpak.h mfx/mfxplugin.h mfx/mfxsession.h mfx/mfxstructures.h mfx/mfxvideo.h mfx/mfxvp8.h mfx/mfxvstructures.h '//home/brian/ffmpeg_build/include/mfx'
make[1]: Leaving directory '/home/brian/mfx_dispatch'

**Comment by lu-zero** [comment]
Btw, please try to use either the mfx examples or libav, if you have problem with some other software you should ask to who develops that software.

**Comment by maximd33** [comment]
@rdp hmmm , do you know how to implement such ?

**Comment by rdp** [comment]
It didn't look easy... :)

On Saturday, August 4, 2018, maximd33 <notifications@github.com> wrote:
> @rdp hmmm , do you know how to implement such ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/BHpTIObW3jwwNrtew_EPXGk-ixHcjKdJbNMeQ2IQydADTW_67fjqA0CANdY0TRdwtSkVOnCjg7mD0AB1Bb-LWZLp8iXg51i_t8yyTCPRF6halN-lwbhfzNqCq77EEAqPyRJBJXi-kfW_Cdt_HCQLu13YWLeUpQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0NzoTWGvsNfxaU_IO9gGY-gg-tVAks5uNhqygaJpZM4HH-46.gif>
