### ISSUE TITLE
How to install in order to compile ffmpeg using mingW32

### ISSUE THREAD

**Issue by francescoBLT** [lu-zero/mfx_dispatch#25]
Hi to all
I'm a little new so I apologize if my question seems stupid....
I download the package under Windows XP and compiled it using Visual Studio 2010.
Now I have the libmfx_d.lib.  How can I install in mingw ?
Should I copy the file libmfx.pc into directory c:\MingW\lib\pkgconfig ?
In the c:\MingW\lib directory all libraries have a ".a" extension and shouldn't be compatible
with the ".lib" generated by VS2010.
Regards

**Comment by lu-zero** [comment]
It is not related to mfx_dispatch, please ask for support to that project.
