### ISSUE TITLE
Provide releases in the form of tags

### ISSUE THREAD

**Issue by naftulikay** [lu-zero/mfx_dispatch#26]
Currently, there's only really a master branch and it's hard to package against Git commit hash ids. Can you please tag significant releases?

Even if you're not following upstream's tag model (I think latest upstream is 1.6.0), just giving SemVer tag names would be very helpful.

**Comment by lu-zero** [comment]
It makes sense indeed.

**Comment by lu-zero** [comment]
Implemented :)
