### ISSUE TITLE
Error initializing an internal MFX session

### ISSUE THREAD

**Issue by metabubble** [lu-zero/mfx_dispatch#28]
Hi,

I am on debian testing and I tried to get ffmpeg working. What I did so far was:

`apt-get build-dep ffmpeg # pulls all the -dev packages`
`apt-get install libva-dev`

checked out mfx_dispatch master and executed statements

`autoreconf -i
./configure --prefix=/usr
make -j 18
make install`

Then I got the ffmpeg master from git and configured with:

`./configure --disable-shared --enable-static --enable-gpl --enable-nonfree --enable-fontconfig --enable-libfreetype --enable-libmp3lame --enable-librtmp  --enable-libx264 --enable-libx265 --enable-version3 --disable-ffplay --disable-doc --disable-ffserver --enable-pthreads --enable-filters --enable-libvorbis --enable-libtheora --enable-runtime-cpudetect --enable-libass --enable-bzlib --enable-zlib  --enable-libmfx --prefix=/opt/ffmpeg_qsv/`

But whenever I run (even as root) ffmpeg from that path, I get

```
[hevc_qsv @ 0x344aba0] Error initializing an internal MFX session
Output #0, matroska, to 'output.mkv':
    Stream #0:0: Video: hevc, none, q=2-31, 128 kb/s, SAR 1:1 DAR 0:0, 23.98 fps
    Metadata:
      encoder         : Lavc57.28.101 hevc_qsv
    Stream #0:1(eng): Audio: ac3, 48000 Hz, stereo, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> hevc (hevc_qsv))
  Stream #0:1 -> #0:1 (copy)
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

Where am I going wrong?

**Comment by lu-zero** [comment]
FFmpeg is not supported to begin with sorry =)
