### ISSUE TITLE
Error initializing an internal MFX session

### ISSUE THREAD

**Issue by ladesma** [lu-zero/mfx_dispatch#30]
Good afternoon, I have problem with the h264_qsv encoder. I saw this error (in ubuntu machine) when I was trying to make transcoding:
 “[swscaler @ 0x27763e0] deprecated pixel format used, make sure you did set range correctly
[h264_qsv @ 0x269cba0] Error initializing an internal MFX session
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height” 
I used the following command “ffmpeg -i video.mp4 -c:v h264_qsv -preset:v faster out.mp4”
I have installed libva, libdrm, libva-intel-driver , mfx_dispatch(from https://github.com/lu-zero/mfx_dispatch) with these instructions:
autoreconf -i
./configure --prefix=/usr
make -j 18
make install
and finally ffmpeg with ./configure enable-libmfx, make and make install.
Aditionally I can see this message if I try to see what hardware accelerations are enable“Supported hwaccels: qsv”.

**Comment by lu-zero** [comment]
require assistance directly to FFmpeg please.
