### ISSUE TITLE
Error running QSV encoder on Ubuntu 16.04

### ISSUE THREAD

**Issue by rauldipeas** [lu-zero/mfx_dispatch#32]
I build FFMPEG with NVENC and QSV support on Ubuntu 16.04, but when I try to run SimpleScreenRecorder, I get this error:

[h264_qsv @ 0x2348400] Error initializing an internal MFX session

[Here](http://avix.esy.es/ffmpeg-nvenc+quicksync.sh) is the script that I use to build MFX-Dispatch and FFMPEG.

**Comment by lu-zero** [comment]
Please ask FFmpeg.
