### ISSUE TITLE
Update to upstream 1.19 sdk

### ISSUE THREAD

**Issue by Sibras** [lu-zero/mfx_dispatch#34]
The current repo is only at version 1.16 which missed some of the more advanced capabilities that can be utilized on newer hardware. Updating to the latest (at time of writing 1.19) would be appreciated.

I have performed the update locally and attached a patch that will add the required updates.

[https://gist.github.com/Sibras/158ebce11b7e0b406a80b52305e935f2](https://gist.github.com/Sibras/158ebce11b7e0b406a80b52305e935f2)

**Comment by lu-zero** [comment]
If you open a pull request I'll update immediately. Otherwise I'll just merge it manually.

Thank you a lot!

**Comment by Sibras** [comment]
Created a pull request.

**Comment by lu-zero** [comment]
Merged =)
