### ISSUE TITLE
Compile error in mfx_plugin_hive_linux.cpp

### ISSUE THREAD

**Issue by bermond** [lu-zero/mfx_dispatch#36]
I'm getting the following error in ```mfx_plugin_hive_linux.cpp``` when trying to compile libmfx:
```
src/mfx_plugin_hive_linux.cpp:38:35: fatal error: mfx_plugin_cfg_parser.h: No such file or directory
 #include "mfx_plugin_cfg_parser.h"
                                   ^
compilation terminated.
make: *** [Makefile:763: src/libmfx_la-mfx_plugin_hive_linux.lo] Error 1
```

This error is caused by the recent git commits from October 9, 2016. It was compiling well before these commits.

Commands used:
```
$ git clone https://github.com/lu-zero/mfx_dispatch.git libmfx-git
$ cd libmfx-git
$ autoreconf -i
$ ./configure \
                --prefix=/usr \
                --enable-static=yes \
                --enable-shared=no \
                --enable-fast-install=yes \
                --with-libva_drm=yes \
                --with-libva_x11=yes \
                --with-pic
$ make -j1
```

**System information (version):**
**OS:** Arch Linux x86_64
**libmfx:** git master (currently at r42.f9e3baa)
**GCC:** 6.2.1
**glibc:** 2.24
**libva:** 1.7.2
**CPU:** Intel Haswell

Any help or comment would be appreciated.
Thank you.

**Comment by lu-zero** [comment]
Looks like the last update did break linux, could you please try to `git pull --rebase` and try again?

**Comment by bermond** [comment]
@lu-zero 
Thank you for the support and reply.

Doing a ```git pull --rebase``` didn't worked and the same error persisted. But making a new ```git clone``` worked and the compilation is going fine again.

I know that maybe it's not directly related to this, but after this update in libmfx ffmpeg (git master) doesn't recognize libmfx anymore at configure time and gives this: ```ERROR: libmfx not found using pkg-config```.  Is it normal and do they need to add some changes in order to ffmpeg to be compliant with this update?

**Comment by lu-zero** [comment]
Probably there is yet something missing in the update, please `git fetch --all && git reset --hard origin/master` and build again.

**Comment by bermond** [comment]
Yes, something really weird happened in Arch build tree after your fix. Deleted and recompiled everything again in and all is fine.
Again, thanks for the support.

**Comment by lu-zero** [comment]
I didn't verify fully that the version bump was working on both platforms, thank you for reporting the problem precisely =)

**Comment by bermond** [comment]
It was a pleasure to contribute in some way, and it always will be. I'm maintaining libmfx-git package for the AUR.
