### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dbermond** [lu-zero/mfx_dispatch#37]
I'm getting the following error when trying to compile libmfx:

```
In file included from src/mfx_dispatcher.h:38:0,
                 from src/main.cpp:31:
src/mfx_exposed_functions_list.h: In function ‘mfxStatus MFXVideoCORE_SetHandle(mfxSession, mfxHandleType, mfxHDL)’:
src/mfx_exposed_functions_list.h:54:21: error: redefinition of ‘mfxStatus MFXVideoCORE_SetHandle(mfxSession, mfxHandleType, mfxHDL)’
 FUNCTION(mfxStatus, MFXVideoCORE_SetHandle, (mfxSession session, mfxHandleType type, mfxHDL hdl), (session, type, hdl))
                     ^
src/mfx_dispatcher_defs.h:83:40: note: in definition of macro ‘DISPATCHER_EXPOSED_PREFIX’
 #define DISPATCHER_EXPOSED_PREFIX(fnc) fnc
                                        ^~~
src/mfx_exposed_functions_list.h:54:1: note: in expansion of macro ‘FUNCTION’
 FUNCTION(mfxStatus, MFXVideoCORE_SetHandle, (mfxSession session, mfxHandleType type, mfxHDL hdl), (session, type, hdl))
 ^~~~~~~~
src/main.cpp:905:11: note: ‘mfxStatus MFXVideoCORE_SetHandle(mfxSession, mfxHandleType, mfxHDL)’ previously defined here
 mfxStatus MFXVideoCORE_SetHandle(mfxSession session, mfxHandleType type, mfxHDL hdl)
           ^~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:670: src/libmfx_la-main.lo] Error 1
```

This error is caused by git commit [8d25a2b5835908836bb03391f262d0bba24af13d](https://github.com/lu-zero/mfx_dispatch/commit/8d25a2b5835908836bb03391f262d0bba24af13d) (the last one at the time of writing). [As you know](https://github.com/lu-zero/mfx_dispatch/issues/36), it was compiling perfectly one commit before this one.

Commands used:

```
$ git clone https://github.com/lu-zero/mfx_dispatch.git libmfx-git
$ cd libmfx-git
$ autoreconf -i
$ ./configure \
                --prefix=/usr \
                --enable-static=yes \
                --enable-shared=no \
                --enable-fast-install=yes \
                --with-libva_drm=yes \
                --with-libva_x11=yes \
                --with-pic
$ make -j1
```

**System information:**
**OS:** Arch Linux x86_64
**libmfx:** git master (currently at r42.8d25a2b)
**GCC:** 6.2.1
**glibc:** 2.24
**libva:** 1.7.2
**CPU:** Intel Haswell

Any help or comment would be appreciated.
Thank you.

**Comment by lu-zero** [comment]
I tried to unbreak it, but it is an ongoing process, please wait for the weekend, the update patch broke linux in quite not so funny ways, probably I'll have to undo it completely and redo it on my own.

**Comment by bermond** [comment]
Thank you for the reply and support. And sorry if I'm excessively reporting this errors.

**Comment by lu-zero** [comment]
The sooner it is reported the sooner is fixed, if you are on irc we can try there to make sure everything is ok in a more interactive way =)

**Comment by bermond** [comment]
Surely. :)
What is the network and channel?

**Comment by lu-zero** [comment]
This should be solved since a while.
