### ISSUE TITLE
undefined reference to `MFXInit'

### ISSUE THREAD

**Issue by odessky** [lu-zero/mfx_dispatch#4]
Hi

I was success install dispatcher on my server:

root@server4:~/mfx_dispatch# cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
-- Intel Media SDK is here: /root/mfx_dispatch
-- Configuring done
-- Generating done
-- Build files have been written to: /root/mfx_dispatch
root@server4:~/mfx_dispatch#  make -j
[ 25%] [ 25%] [ 25%] [ 33%] [ 41%] Building CXX object CMakeFiles/mfx.dir/src/main.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_critical_section_linux.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_critical_section.cpp.o
[ 58%] [ 58%] Building CXX object CMakeFiles/mfx.dir/src/mfx_dispatcher.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_dxva2_device.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_dispatcher_log.cpp.o
[ 66%] [ 75%] Building CXX object CMakeFiles/mfx.dir/src/mfx_function_table.cpp.o
[ 83%] [ 91%] [100%] Building CXX object CMakeFiles/mfx.dir/src/mfx_library_iterator.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_load_dll.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_library_iterator_linux.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_load_dll_linux.cpp.o
Building CXX object CMakeFiles/mfx.dir/src/mfx_win_reg_key.cpp.o
Linking CXX static library libmfx.a
[100%] Built target mfx
root@server4:~/mfx_dispatch# make install
[100%] Built target mfx
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/mfxmvc.h
-- Installing: /usr/local/include/mfxstructures.h
-- Installing: /usr/local/include/mfxastructures.h
-- Installing: /usr/local/include/mfxvideo.h
-- Installing: /usr/local/include/mfxaudio.h
-- Installing: /usr/local/include/mfxsession.h
-- Installing: /usr/local/include/mfxvstructures.h
-- Installing: /usr/local/include/mfxjpeg.h
-- Installing: /usr/local/include/mfxaudio++.h
-- Installing: /usr/local/include/mfxcommon.h
-- Installing: /usr/local/include/mfxla.h
-- Installing: /usr/local/include/mfxdefs.h
-- Installing: /usr/local/include/mfxenc.h
-- Installing: /usr/local/include/mfxplugin.h
-- Installing: /usr/local/include/mfxvideo++.h
-- Installing: /usr/local/include/mfxplugin++.h
-- Installing: /usr/local/lib/pkgconfig/libmfx.pc
-- Installing: /usr/local/lib/libmfx.a

After I try configure libav-qsv, I get error:
root@server4:~/libav-qsv# ./configure --enable-libmfx --enable-memalign-hack --extra-libs="-lsupc++ -lstdc++"
ERROR: libmfx not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
libav-tools@libav.org mailing list or IRC #libav on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solving the problem

There is last strings related dispatcher:

gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -std=c99 -fomit-frame-pointer -pthread -I/usr/local/include -I/root/mfx_dispatch /usr/local/lib/libmfx.a -L/usr/local/lib -c -o /tmp/ffconf.ULRa4u11.o /tmp/ffconf.bSVvuwIW.c
gcc: warning: /usr/local/lib/libmfx.a: linker input file unused because linking not done
gcc -Wl,--as-needed -I/usr/local/include -I/root/mfx_dispatch /usr/local/lib/libmfx.a -L/usr/local/lib -o /tmp/ffconf.6X5q3o0K /tmp/ffconf.ULRa4u11.o -lsupc++ -lm -lbz2 -lz -pthread -lsupc++ -lstdc++
/tmp/ffconf.ULRa4u11.o: In function `check_MFXInit':
ffconf.bSVvuwIW.c:(.text+0x1): undefined reference to `MFXInit'
collect2: error: ld returned 1 exit status
ERROR: libmfx not found

Can you help my understand why I get this error?

**Comment by lu-zero** [comment]
I updated the https://github.com/lu-zero/libav/tree/qsv with the changes from anton, could you please test if it builds and runs on windows as well? It is the decoder, I'll update the encoder hopefully this weekend.

**Comment by lu-zero** [comment]
The new code from Anton is in mainline and had been tested on both platforms.
