### ISSUE TITLE
struct VADriverContext' has no member named 'drm_state'

### ISSUE THREAD

**Issue by minimal101** [lu-zero/mfx_dispatch#5]
root@qsv:~/mfx_dispatch# git clone https://github.com/lu-zero/mfx_dispatch.git
root@qsv:~/mfx_dispatch# mv mfx/ mfx_old
root@qsv:~/mfx_dispatch# ln -s /opt/intel/mediasdk/include/ /root/mfx_dispatch/mfx
root@qsv:~/mfx_dispatch# autoreconf -i
root@qsv:~/mfx_dispatch# ./configure --prefix=/usr/local
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBVA_DRM... yes
checking for LIBVA_X11... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking how to print strings... printf
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating libmfx.pc
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
root@qsv:~/mfx_dispatch# make -j
depbase=`echo src/mfx_va_glue.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/bash ./libtool --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" -DPACKAGE_STRING=\"libmfx\ 1.7\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.7\" -DMFX_HAVE_LINUX=1 -DHAVE_LIBVA_DRM=1 -DHAVE_LIBVA_X11=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.  -I./include -DMINGW_HAS_SECURE_API=1   -g -O2 -MT src/mfx_va_glue.lo -MD -MP -MF $depbase.Tpo -c -o src/mfx_va_glue.lo src/mfx_va_glue.c &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" "-DPACKAGE_STRING=\"libmfx 1.7\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.7\" -DMFX_HAVE_LINUX=1 -DHAVE_LIBVA_DRM=1 -DHAVE_LIBVA_X11=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -DMINGW_HAS_SECURE_API=1 -g -O2 -MT src/mfx_va_glue.lo -MD -MP -MF src/.deps/mfx_va_glue.Tpo -c src/mfx_va_glue.c  -fPIC -DPIC -o src/.libs/mfx_va_glue.o
src/mfx_va_glue.c: In function 'mfx_deallocate_va':
src/mfx_va_glue.c:80:19: error: 'struct VADriverContext' has no member named 'drm_state'
make: *** [src/mfx_va_glue.lo] Error 1

whats a problem?

**Comment by lu-zero** [comment]
sorry for the horrible delay probably your headers do not have that field for some reasons but it build fine for me here with the same nominal version (and libva-1.1.1 as specific version)

**Comment by minimal101** [comment]
never mind !! actualy we solved using https://github.com/shenhailuanma/qsv-ffmpeg-codec !
