### ISSUE TITLE
Align mfx header install destination path with open source msdk

### ISSUE THREAD

**Issue by sreerenjb** [lu-zero/mfx_dispatch#50]
Just found that the Open source MSDK ( https://github.com/Intel-Media-SDK/MediaSDK) has all headers under PREFIX/include. Would it be better to use the same path for mfx_dispatch too (currently it is PREFIX/include/mfx)?
GStreamer  (gst-plugins-bad) has support for mfx_dispatch where it searches for headers under "PREFIX/include/mfx" but this fails with open source msdk.

**Comment by lu-zero** [comment]
Maybe could be nicer if the other variant adds a mfx subdirectory having that many headers in the include path isn't exactly nice.

Could you please open an issue on their side as well and refer to this one?

**Comment by sreerenjb** [comment]
Just saw this: https://github.com/Intel-Media-SDK/MediaSDK/issues/199 :)

**Comment by maximd33** [comment]
yeap, let's be driven from #199

**Comment by lu-zero** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/commit/6f26423a3091b429365fbdae2dfb26ae93773ddb fixed the problem on their side.
