### ISSUE TITLE
Add license info to repo

### ISSUE THREAD

**Issue by kathenas** [lu-zero/mfx_dispatch#52]
Could license data related to the project and its code be added to the repo please. This would clarify for projects and allow in decision making to add to projects or distros or not.

**Comment by lu-zero** [comment]
It is present since the [beginning](https://github.com/lu-zero/mfx_dispatch/blob/master/COPYING), or I'm missing something?

**Comment by kathenas** [comment]
Semi my issue here. As one that looks at code more often than recognizing licenses. The COPYING is BSD clause 3, but would be nice if that was stated somewhere to add clarity.

**Comment by lu-zero** [comment]
If you have something specific in mind I'm open to add it :)

**Comment by kathenas** [comment]
If you create a duplicate of COPYING and call it LICENSE and add it to the repo. The repo will be marked indicating the contents of the license file.

Example below...

![screenshot from 2018-06-30 16-12-11](https://user-images.githubusercontent.com/38569353/42126422-695533ea-7c80-11e8-9416-2984bd55b089.png)

Adds a visible license indicator and link to license file.

**Comment by lu-zero** [comment]
Send a pull request and I'll merge it immediately :)

**Comment by kathenas** [comment]
PR #53

**Comment by lu-zero** [comment]
I merged your change but I'm not seeing any license indicator though...

**Comment by maximd33** [comment]
@kathenas thanks for the contribution

**Comment by kathenas** [comment]
@lu-zero The template auto recognized by github required some tweaking of files in the repo. see PR #54.

**Comment by kathenas** [comment]
See test repo for a working version. https://github.com/kathenas/test_001

**Comment by lu-zero** [comment]
We should be set now. Thanks a lot!
