### ISSUE TITLE
no release for 1.25

### ISSUE THREAD

**Issue by rathann** [lu-zero/mfx_dispatch#55]
It looks like the code was updated to match 1.25 version in 613c5c7aadf09b590ec135302bf8974a3eccb880 but there's no corresponding release. Could you make one?

**Comment by lu-zero** [comment]
Sure, let me know if it works for you.

**Comment by rathann** [comment]
Looks (and builds) fine. There are no backwards-incompatible ABI changes, either. Thanks.
