### ISSUE TITLE
VA Initialization dropped

### ISSUE THREAD

**Issue by jstebbins** [lu-zero/mfx_dispatch#59]
Hi,  I notice that in @maximd33 last commit to update to 1.27 that the code to initialize VA for linux got dropped. Specifically all the internal_hwctx stuff is gone.  Was that intentional?  HandBrake recently updated to your latest and coincidentally I happened to try building HandBrake on Linux with QSV enabled for the first time and discovered this.  I've already created a patch on our side that resolves it by initializing VA and calling SetHandle, but just wanted to check if this was an intentional change in behavior.

**Comment by lu-zero** [comment]
I started to suggest to use the fully opensource mediasdk from intel on linux so I overlooked that part.

If you could try it with and w/out your patch would be great :)

**Comment by jstebbins** [comment]
By "try it" are you referring to mediasdk's mfx_dispatch?

**Comment by lu-zero** [comment]
https://github.com/Intel-Media-SDK/MediaSDK this as whole :)

**Comment by jstebbins** [comment]
Right.  I'm already using the rest of that (built and installed separately from HandBrake). I'm just not using the mfx_dispatch part.  I can certainly give it a try.  MediaSDK builds mfx_dispatch only shared, and HandBrake links static, but that's easily patched.

**Comment by jstebbins** [comment]
Verified, the MediaSDK version behaves the same in some brief tests.

**Comment by jstebbins** [comment]
FYI mfx_dispatcher https://github.com/Intel-Media-SDK/MediaSDK is for linux only.  It is missing all the stuff for loading d3d on windows that your fork has.

**Comment by lu-zero** [comment]
That's why I suggest the MediaSDK only on Linux and I keep this mfx_dispatch available for windows :)

**Comment by maximd33** [comment]
please consider https://github.com/lu-zero/mfx_dispatch/pull/67
