### ISSUE TITLE
update to 1.30

### ISSUE THREAD

**Issue by rathann** [lu-zero/mfx_dispatch#66]
1.30 seems to be out (included in Intel MediaSDK 19.3: https://github.com/Intel-Media-SDK/MediaSDK/tree/master/api/include/mfxdefs.api#L24). I think you made some commits updating to 1.27, but never made a release out of that, either.

https://github.com/lu-zero/mfx_dispatch/blob/master/libmfx.pc.cmake#L8 seems to have a hard-coded version. Is that on purpose?

**Comment by maximd33** [comment]
1.30 update is considered, if you wish to help - welcome

dont see any specific reasons

**Comment by maximd33** [comment]
https://github.com/lu-zero/mfx_dispatch/pull/67 should close this issue
