### ISSUE TITLE
Is the Intel SDK really required?

### ISSUE THREAD

**Issue by mjb2000** [lu-zero/mfx_dispatch#7]
This might be a silly question, but is the Intel SDK actually required to be installed on the computer which you are using to build libmfx?

I have tried building libmfx on Windows in MinGW and it seems to build just fine without the Intel SDK ever being installed. The files generated are libmfx.a (254KB) and libmfx.la (1KB).

Does this sound correct to you? Using this build (without the SDK) I was able to compile ffmpeg + qsv

(confused!)

**Comment by lu-zero** [comment]
If you want to run the qsv code you need the firmware and the hybrid decoders.

**Comment by elthariel** [comment]
libmfx is actually a weird wrapper to load the correct implementation at runtime. So it'll build and load without the sdk but you won't be able to do anything with it :)

**Comment by lu-zero** [comment]
Sorry to repeat myself, ffmpeg is not supported.
