### ISSUE TITLE
src/main.cpp:21:10: fatal error: windows.h: No such file or directory

### ISSUE THREAD

**Issue by aphex3k** [lu-zero/mfx_dispatch#71]
```
sudo apt-get install -y libva-dev vainfo
git clone --depth=1 https://github.com/lu-zero/mfx_dispatch.git
cd mfx_dispatch
autoreconf -i                           
./configure --prefix=/usr
make -j$(nproc)
```

It fails with the following error:

```
src/main.cpp:21:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:702: recipe for target 'src/libmfx_la-main.lo' failed
make: *** [src/libmfx_la-main.lo] Error 1
```

**Comment by lu-zero** [comment]
If you are on linux I suggest to use the [media-sdk](https://github.com/Intel-Media-SDK/MediaSDK) for the time being, if you are on windows, could you please give us more information on what is your environment?

**Comment by solabc16** [comment]
Hello @aphex3k 

I'm just been looking at options for this as well - for Linux, what path did you take as a workaround?

Best
- James

**Comment by aphex3k** [comment]
> Hello @aphex3k 
> 
> 
> 
> I'm just been looking at options for this as well - for Linux, what path did you take as a workaround?
> 
> 
> 
> Best
> 
> - James

I did not pursue this any further

**Comment by kloczek** [comment]
BTW: It would be good as well to remove exec atribute from mfx/*.h files in git repo.

**Comment by kloczek** [comment]
I want only confirm that https://github.com/lu-zero/mfx_dispatch/commit/6e050af0a8ebadf91b0ab6d395b4cd083afddfa0 fixed the build issue.
Thank you :)
