### ISSUE TITLE
Fix the CI support

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/mfx_dispatch#74]
something seems broken in the msys2 update.

**Comment by lu-zero** [comment]
@luni-4 could you have a look if you have time please?

**Comment by 1480c1** [comment]
you probably can remove most of the beginning parts since github actions now has msys2 in C:\msys64 by default

**Comment by 1480c1** [comment]
so remove the lines from `Get msys2` step except the
```powershell
Write-Output "::add-path::C:/msys64/usr/bin"
Write-Output "::add-path::C:/msys64/mingw64/bin"
```

**Comment by lu-zero** [comment]
Let's try :)
