### ISSUE TITLE
QuickSync not working in ffmpeg and libav

### ISSUE THREAD

**Issue by mjb2000** [lu-zero/mfx_dispatch#8]
Hi @lu-zero 

I've run in to a couple of potential problems with:
* [droncon11/ffmpeg](https://github.com/drocon11/ffmpeg-qsv)
* [mjb2000/ffmpeg](https://github.com/mjb2000/FFmpeg)
* [lu-zero/libav/tree/qsvenc](https://github.com/lu-zero/libav/tree/qsvenc)
* [drocon11/libav-qsv](https://github.com/drocon11/libav-qsv)

I have only seen these issues on my Intel J1900 CPU, my Intel i7-4770 does not have these problems. It's tempting just to blame my hardware, but I have done similar tests with [Handbrake](https://handbrake.fr/nightly.php) and [q264](http://www.tetrachromesoftware.com/) and they are not affected by either of these issues...

## Issue 1 - jumpy output
Take a look at these two example files:

Original: http://data.purplepixelmedia.co.uk/30seconds.mp4
QSV encoded: http://data.purplepixelmedia.co.uk/30seconds-qsv_out.mp4

You can see in the original that the frame numbers should count up sequentially, but in the qsv output, the time 'jumps' around. The command I ran to create the qsv encoded version was:
`ffmpeg -i 30seconds.mp4 -map 0:0 -b:v 1000K -c:v h264_qsv  30seconds-qsv_out.mp4`

Interestingly, if I resize the video to 1280x720 then the output is fine (but noticeably slower) - the command for this was
`ffmpeg -i 30seconds.mp4 -map 0:0 -s 1280x720 -b:v 1000K -c:v h264_qsv  30seconds-qsv_out720p.mp4`

I have tied other clips which are 1280x720 to start with, but if I don't resize them, then I get the same 'jumping' problem. **It seems that by forcing ffmpeg to do some processing that this fixes the jumping problem, but if the video is not resized, then it does not work properly.**

Going through the output.mp4 frame-by-frame you can see that it always skips back exactly 4 frames, but at seemingly random times through the video. I'm not sure if this 4 frame jump gives any clues as to what might be going wrong?

## Issue 2 - not working after driver update

I hoped I might be able to fix the issue by updating my driver, but unfortunately this stopped ffmpeg and libav working entirely when trying to use QuickSync. The encoder just sits there and doesn't actually encode anything (I need to use CTRL+C to abort and return to the command prompt).

* Driver: 10.18.10.3408 (20/01/2014) - Working (but with the jumpy encoding mentioned above)
* Driver: 10.18.10.3958 (30/09/2014) - Not working

I'd be happy to put this down to a driver issue, but as I mentioned above, [Handbrake](https://handbrake.fr/nightly.php) and [q264](http://www.tetrachromesoftware.com/) both continue to work perfectly with QuickSync.

Any idea what could be going wrong?

**Comment by mjb2000** [comment]
Hi Luca - Happy new year :)

Have you and the libav team been able to work out what might be going wrong here? I am building ffmpeg+h264_qsv to enable GPU transcoding of video in the [MediaBrowser](http://mediabrowser.tv) project. [Someone on the forum](http://mediabrowser.tv/community/index.php?/topic/10723-gpu-transcoding-intel-quicksync-and-nvidia-nvenc/?p=167322) has recently found that it is not working for him on Windows 2012R2 with the latest drivers and an i7 4770 CPU - I imagine it is related to the same issue affecting my chip.

**Comment by lu-zero** [comment]
Anton is working on the decoding part and I plan to spend few days on the
encoding side soon.

Again, our project is Libav and having people asking us to fix bugs or add
features just to use (and suggest to use) FFmpeg once we do the work is
always quite demotivating...

**Comment by mjb2000** [comment]
Sorry Luca, I do understand. Unfortunately don't control MediaBrowser so I'm tied to using the tool they are already using. From what I've read ffmpeg effectively 'steals' the code from libav and uses it within it's 'libavcodec' - I can see why this would be frustrating.

MediaBrowser are using ffmpeg to transcode source medial files for live streaming to various devices (such as Roku, Android and Smart TVs) - They use VPX and x264 with various scaling and deinterlacing options. I guess there is no reason they can't use libav for this? - I'll put in a good word! :)

**Comment by lu-zero** [comment]
The support for QSV had been merged in the mainline Libav, I updated the dispatcher to match the Intel improved API now.
