### ISSUE TITLE
windows xp not working?

### ISSUE THREAD

**Issue by rdp** [lu-zero/mfx_dispatch#9]
Hello, as a note, got this message under xp [?]
procedure entry point wfopen_s could not be located in msvcrt.dll or some odd.
Cheers!

**Comment by filler56789** [comment]
IF the code is not compatible with Windows XP because of the Intel media SDK itself,
THEN please update the README.md file.
Otherwise, please fix your sorce-code.
Just my 2 euros.

**Comment by justa9** [comment]
Any update on this?

**Comment by lu-zero** [comment]
Please do try the upstream version first if you are using windows. Intel provides also prebuilt version that you can use with msvc.

**Comment by sr55** [comment]
If I recall correctly, the _s variants are "security enhanced" versions of the methods. These were only backported as far as Windows Vista so won't work in XP and earlier. 

I spotted chrome doing something like this:

#ifdef __MINGW32__ 
#include <_mingw.h> 
#ifdef MINGW_HAS_SECURE_API 

however, I suspect the driver simply won't support it anyway.

**Comment by rdp** [comment]
Could you give a pointer as to where to find the upstream version for me by chance?  Are you referring to intel's own download? Thanks!

**Comment by native-api** [comment]
As per http://stackoverflow.com/questions/1073509/should-i-redistribute-msvcrt-dll-with-my-application and specifically https://blogs.msdn.microsoft.com/oldnewthing/20140411-00/?p=1273 , 3rd party apps must not link against the system's `msvcrt` but use a specific version of VC redistributable instead.

**Comment by rdp** [comment]
linking against mingwex might help, or so I've been told...

**Comment by sr55** [comment]
Not going to help if there is no driver support for the hardware.

**Comment by lu-zero** [comment]
Is the solution from @Sibras working for you?

**Comment by lu-zero** [comment]
I assume it does. Reopen otherwise.
